# Generated by Django 4.1.3 on 2022-11-23 19:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosUsuarios',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField()),
                ('is_staff', models.BooleanField()),
                ('tipo_usuario', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'usuarios_usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_ped', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('descrip', models.CharField(max_length=200)),
                ('estado_admin', models.BooleanField(default=False)),
                ('estado_productor', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'PEDIDO',
            },
        ),
        migrations.CreateModel(
            name='ProcesPedido',
            fields=[
                ('id_proc_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('estado_proceso', models.BooleanField(default=False)),
                ('pedido_id_ped', models.ForeignKey(db_column='pedido_id_ped', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.pedido')),
            ],
            options={
                'verbose_name': 'Procesar Pedido',
                'verbose_name_plural': 'Procesar Pedidos',
                'db_table': 'PROCESAR_PEDIDO',
            },
        ),
        migrations.CreateModel(
            name='ProcesVenta',
            fields=[
                ('id_proc_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('proces_pedido_id_proc_pedido', models.ForeignKey(db_column='proces_pedido_id_proc_pedido', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.procespedido')),
            ],
            options={
                'verbose_name': 'Procesar Venta',
                'verbose_name_plural': 'Procesar Ventas',
                'db_table': 'PROCESO_VENTA',
            },
        ),
        migrations.CreateModel(
            name='VentLocal',
            fields=[
                ('id_vent_loc', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_cli', models.CharField(max_length=20)),
                ('ape_pat', models.CharField(max_length=20)),
                ('ape_mat', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('proces_venta_id_proc_venta', models.ForeignKey(db_column='proces_venta_id_proc_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.procesventa')),
            ],
            options={
                'verbose_name': 'Venta Local',
                'verbose_name_plural': 'Ventas Locales',
                'db_table': 'VENTA_LOCAL',
            },
        ),
        migrations.CreateModel(
            name='VentExtran',
            fields=[
                ('id_vent_ex', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_cli', models.CharField(max_length=20)),
                ('ape_pat', models.CharField(max_length=20)),
                ('ape_mat', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('proces_venta_id_proc_venta', models.ForeignKey(db_column='proces_venta_id_proc_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.procesventa')),
            ],
            options={
                'verbose_name': 'Venta Extranjera',
                'verbose_name_plural': 'Ventas Extranjeras',
                'db_table': 'VENTA_EXTRANJERO',
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_trans', models.AutoField(primary_key=True, serialize=False)),
                ('tip_transporte', models.CharField(max_length=15)),
                ('tamano_trans', models.IntegerField()),
                ('capacidad_trans', models.IntegerField()),
                ('refrigeracion_trans', models.CharField(max_length=10)),
                ('fecha_trans', models.DateField()),
                ('usuarios_usuarios_id_user', models.ForeignKey(db_column='usuarios_usuarios_id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.usuariosusuarios')),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
                'db_table': 'TRANSPORTE',
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('est_seguimiento', models.CharField(choices=[('preparando', 'preparando productos'), ('despacho', 'productos despachados'), ('recepcionados', 'recepcionados por el transportista'), ('viaje', 'en camino'), ('completado', 'seguimiento finalizado')], default='preparando', max_length=50)),
                ('pedido_id_ped', models.ForeignKey(db_column='pedido_id_ped', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.pedido')),
                ('proces_pedido_id_proc_pedido', models.ForeignKey(db_column='proces_pedido_id_proc_pedido', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.procespedido')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimiento',
                'db_table': 'SEGUIMIENTO',
            },
        ),
        migrations.CreateModel(
            name='ReportVenta',
            fields=[
                ('id_report_vent', models.IntegerField(primary_key=True, serialize=False)),
                ('prod_venta', models.CharField(max_length=20)),
                ('cant_venta', models.IntegerField()),
                ('total_venta', models.IntegerField()),
                ('proces_venta_id_proc_venta', models.ForeignKey(db_column='proces_venta_id_proc_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.procesventa')),
            ],
            options={
                'verbose_name': 'Reportar Venta',
                'verbose_name_plural': 'Reportar Ventas',
                'db_table': 'REPORTE_VENTA',
            },
        ),
        migrations.CreateModel(
            name='ReportMerma',
            fields=[
                ('id_merma', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_merma', models.DateField()),
                ('descrip_merma', models.CharField(max_length=40)),
                ('usuarios_usuarios_id_user', models.ForeignKey(db_column='usuarios_usuarios_id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.usuariosusuarios')),
            ],
            options={
                'verbose_name': 'Reportar Merma',
                'verbose_name_plural': 'Reportar Mermas',
                'db_table': 'REPORTE_MERMA',
            },
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id_report', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_report', models.DateField()),
                ('tip_report', models.CharField(max_length=15)),
                ('user_report', models.CharField(max_length=15)),
                ('descrip_report', models.CharField(max_length=30)),
                ('usuarios_usuarios_id_user', models.ForeignKey(db_column='usuarios_usuarios_id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.usuariosusuarios')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'REPORTES',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prod', models.CharField(max_length=20)),
                ('precio_prod', models.IntegerField()),
                ('desc_prod', models.CharField(max_length=200)),
                ('imagen', models.ImageField(null=True, upload_to='img')),
                ('stock_prod', models.IntegerField()),
                ('usuarios_usuarios_id_user', models.ForeignKey(db_column='usuarios_usuarios_id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.usuariosusuarios')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'PRODUCTOS',
            },
        ),
        migrations.AddField(
            model_name='procespedido',
            name='transporte_id_trans',
            field=models.ForeignKey(db_column='transporte_id_trans', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.transporte'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos_id_prod',
            field=models.ForeignKey(blank=True, db_column='productos_id_prod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.productos'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuarios_usuarios_id_user',
            field=models.ForeignKey(db_column='usuarios_usuarios_id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.usuariosusuarios'),
        ),
        migrations.CreateModel(
            name='DirecLocal',
            fields=[
                ('id_direc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('direc_cli', models.CharField(max_length=20)),
                ('num_calle', models.IntegerField(blank=True, null=True)),
                ('depto', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(max_length=20)),
                ('comuna', models.CharField(max_length=20)),
                ('vent_local_id_vent_loc', models.ForeignKey(db_column='vent_local_id_vent_loc', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.ventlocal')),
            ],
            options={
                'verbose_name': 'Direccion Cli_Local',
                'verbose_name_plural': 'Direccion Cli_Locales',
                'db_table': 'DIRECCION_LOCAL',
            },
        ),
        migrations.CreateModel(
            name='DirecExtran',
            fields=[
                ('id_direc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=20)),
                ('direc_cli', models.CharField(max_length=20)),
                ('num_calle', models.IntegerField(blank=True, null=True)),
                ('depto', models.CharField(blank=True, max_length=10, null=True)),
                ('localidad', models.CharField(max_length=20)),
                ('vent_extran_id_vent_ex', models.ForeignKey(db_column='vent_extran_id_vent_ex', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.ventextran')),
            ],
            options={
                'verbose_name': 'Direccion Cli_Extrajero',
                'verbose_name_plural': 'Direccion Cli_Extrajeros',
                'db_table': 'DIRECCION_EXTRANJERO',
            },
        ),
        migrations.CreateModel(
            name='DetallCompra',
            fields=[
                ('id_detall', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_detall', models.DateField()),
                ('nom_producto', models.CharField(max_length=15)),
                ('cost_producto', models.IntegerField()),
                ('iva_producto', models.IntegerField()),
                ('total_compra', models.IntegerField()),
                ('proces_venta_id_proc_venta', models.ForeignKey(db_column='proces_venta_id_proc_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.procesventa')),
            ],
            options={
                'verbose_name': 'Detalle Compra',
                'verbose_name_plural': 'Detalle Compras',
                'db_table': 'DETALLE_COMPRA',
            },
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id_contrat', models.AutoField(primary_key=True, serialize=False)),
                ('rut_person', models.CharField(max_length=20)),
                ('phone_contrat', models.IntegerField()),
                ('emision_contrat', models.DateField(blank=True, default=datetime.date(2022, 11, 23))),
                ('fin_contrat', models.DateField(blank=True, default=datetime.date(2023, 11, 23))),
                ('estado', models.BooleanField(default=False)),
                ('usuarios_usuarios_id_user', models.ForeignKey(db_column='usuarios_usuarios_id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.usuariosusuarios')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'CONTRATOS',
            },
        ),
    ]
